# Generated by Django 4.2.2 on 2023-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_choice_question_delete_blogpost_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('signature', models.CharField(default='Your Name or Favorite Quote', max_length=140)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
